name: motorbike_navigator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  mapbox_maps_flutter: ^1.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  mapbox_search: ^4.2.2
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  envied_generator: ^0.5.4+1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
