name: motorbike_navigator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  mapbox_search: ^4.2.2
  rxdart: ^0.27.7
  collection: ^1.18.0
  http: ^1.2.1
  uuid: ^4.4.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  injectable: ^2.4.1
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  material_design_icons_flutter: ^7.0.7296
  flutter_map_math: ^0.1.7
  auto_route: ^8.2.0
  firebase_core: ^3.1.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  envied_generator: ^0.5.4+1
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  auto_route_generator: ^8.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
