name: CI
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  flutter_analyze_syntax:
    name: Analyze syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create env file
        run: touch .env && echo "${{ secrets.MAPBOX_API_KEYS }}" > .env
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter run build_runner
        run: flutter packages pub run build_runner build
      - name: Flutter analyze
        run: flutter analyze
  flutter_test_main:
    name: Test main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create env file
        run: touch .env && echo "${{ secrets.MAPBOX_API_KEYS }}" > .env
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter run build_runner
        run: flutter packages pub run build_runner build
      - name: Flutter test
        run: flutter test